<<<<<<< HEAD
# Generated by Django 3.2.5 on 2022-02-10 04:44

import datetime
=======
# Generated by Django 3.2.5 on 2021-07-30 21:18

from django.conf import settings
>>>>>>> 8b5c655fcdee22ea1897707dd9c80035e7376f84
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 8b5c655fcdee22ea1897707dd9c80035e7376f84
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=800)),
<<<<<<< HEAD
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Household Essentials', 'Household Essentials'), ('Women', 'Women'), ('Men', 'Men'), ('Young Adult', 'Young Adult'), ('Kids', 'Kids'), ('Shoes', 'Shoes'), ('Baby', 'Baby'), ('Home', 'Home'), ('Furniture', 'Furniture'), ('Kitchen & Dining', 'Kitchen And Dining'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Video Games', 'Video Games'), ('Movies', 'Movies'), ('Music', 'Music'), ('Books', 'Books'), ('Sports & Outdoors', 'Sports And Outdoors'), ('Beauty', 'Beauty'), ('Personal Care', 'Personal Care'), ('Health', 'Health'), ('Pets', 'Pets'), ('Luggage', 'Luggage'), ('School & Office Supplies', 'School And Office Supplies'), ('Party Supplies', 'Party Supplies'), ('Other', 'Other')], max_length=100)),
                ('user', models.EmailField(max_length=254)),
=======
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
>>>>>>> 8b5c655fcdee22ea1897707dd9c80035e7376f84
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('value', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('user', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rreview', to='main_app.order')),
=======
                ('value', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main_app.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
>>>>>>> 8b5c655fcdee22ea1897707dd9c80035e7376f84
            ],
        ),
    ]
