# Generated by Django 3.2.5 on 2021-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='any@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
