# Generated by Django 3.2.5 on 2021-08-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_review_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Household Essentials', 'Household Essentials'), ('Women', 'Women'), ('Men', 'Men'), ('Young Adult', 'Young Adult'), ('Kids', 'Kids'), ('Shoes', 'Shoes'), ('Baby', 'Baby'), ('Home', 'Home'), ('Furniture', 'Furniture'), ('Kitchen & Dining', 'Kitchen And Dining'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Video Games', 'Video Games'), ('Movies', 'Movies'), ('Music', 'Music'), ('Books', 'Books'), ('Sports & Outdoors', 'Sports And Outdoors'), ('Beauty', 'Beauty'), ('Personal Care', 'Personal Care'), ('Health', 'Health'), ('Pets', 'Pets'), ('Luggage', 'Luggage'), ('School & Office Supplies', 'School And Office Supplies'), ('Party Supplies', 'Party Supplies'), ('Other', 'Other')], max_length=100)),
                ('user', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='user_email', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rreview', to='main_app.order'),
        ),
    ]
